# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zWvrF5lqvqKgFhaegjBWrZL4c0tjmsAB
"""

import streamlit as st
import google.generativeai as genai
from elevenlabs import generate, set_api_key
import os

# 1. SETUP - Replace with your actual keys
GEMINI_API_KEY = "AIzaSyAKf-fb84B7zaFClWfUyIF50A4-6VmpHTg"
ELEVENLABS_API_KEY = "sk_bea862e3530e7a709cc6f6eb2185ee5890c4d159004a1def"

genai.configure(api_key=GEMINI_API_KEY)
set_api_key(ELEVENLABS_API_KEY)

# 2. LOAD UNIVERSITY DATA
with open("University_info.txt.txt", "r", encoding="utf-8") as f:
    university_context = f.read()

st.title("🏛️ SASTRA University ParentBot")
st.subheader("English & தமிழ் Voice Assistant")

# 3. CHAT INTERFACE
if "messages" not in st.session_state:
    st.session_state.messages = []

# Display chat history
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# 4. VOICE INPUT (Simplified as Text for this Demo)
prompt = st.chat_input("Ask about Fees, Admissions, or Hostels...")

if prompt:
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # 5. GENERATE RESPONSE USING GEMINI
    model = genai.GenerativeModel('gemini-1.5-flash')

    # System Instruction to use your .txt file
    full_prompt = f"""
    You are the official SASTRA University ParentBot.
    Use the following information to answer: {university_context}

    Rules:
    1. If the user asks in Tamil, reply in Tamil.
    2. If the user asks in English, reply in English.
    3. If the info is not in the text, ask them to contact admissions@sastra.edu. [cite: 34]

    User Question: {prompt}
    """

    response = model.generate_content(full_prompt)
    bot_response = response.text

    # 6. VOICE OUTPUT (ElevenLabs)
    audio = generate(
        text=bot_response,
        voice="Bella", # Use 'Rachel' or 'George' for good multilingual support
        model="eleven_multilingual_v2"
    )

    with st.chat_message("assistant"):
        st.markdown(bot_response)
        st.audio(audio, format="audio/mp3")

    st.session_state.messages.append({"role": "assistant", "content": bot_response})